name: "Bug Report"
description: "Report an issue relevant to the project"
labels: []
body:
- type: textarea
  attributes:
      label: "Important Information"
      description: >
        If describing a bug, or crash, please provide the following:
           - OS
           - The time when the problem started to happen
           - Possible screenshot or video

      value: |-
          - OS :
          - Issue started after the following:
      render: text
  validations:
      required: true
- type: textarea
  attributes:
      label: "Expected Behavior"
      placeholder: "What were you expecting?"
  validations:
      required: true
- type: textarea
  attributes:
      label: "Actual Behavior"
      placeholder: "What happened instead?"
  validations:
      required: true
- type: textarea
  attributes:
      label: "Log File"
      placeholder: "Drag and drop log file here (Don't paste content directly)"
      description: >
          Disclaimer: The log file may contain identifiable information, such as your username.
          Review the log file before sharing and redact any sensitive data if necessary.
  validations:
      required: true
- type: checkboxes
  attributes:
      label: "I carefully read all instruction and confirm that I did the following:"
      options:
          - label: >-
              I produced the log file while the behaviors described in "Actual Behavior" were
              actively observed.
            required: true
          - label: "I attached the full, untruncated log file."
            required: true
