#  Continuous Integration (CI) workflow to build and sign a project artifact
name: Attest

# Controls when the workflow will run
on:
  # Allows this workflow to be run manually from the Actions tab
  workflow_dispatch:
  release:

defaults:
  run:
    working-directory: ./projectApp
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out the repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4
      - run: npm ci && npm run lint && npm run build && npm run test
      - name: Attest
        uses: actions/attest@v2
        with:
            subject-path: 'https://github.com/UniversityOfSaskatchewanCMPT371/term-project-2025-team-1/archive/refs/tags/ID**.tar.gz'
            predicate-type: 'https://slsa.dev/provenance/v1'
            predicate: '{}'