#  Continuous Integration (CI) workflow to build and sign a project artifact
name: Attest

# Controls when the workflow will run
on:
  # Allows this workflow to be run manually from the Actions tab
  workflow_dispatch:
  release:
  push:
    branches: ['loop1dev-dev']

defaults:
  run:
    working-directory: ./projectApp
# A workflow run is made up of one or more jobs that can run sequentially or in parallel

permissions:
  id-token: write
  contents: read
  attestations: write

jobs:
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out the repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4
      - run: npm ci && npm run lint && npm run build && npm run test
      - name: Attest
        uses: actions/attest-build-provenance@v2
        with:
            subject-path: '/releases/tag/ID1**/'