#  Continuous Integration (CI) workflow to build and test our TS/JS project
name: BuildandTest

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events
  push:
    branches: ['**']
  pull_request:
    branches: ['**']

  # Allows this workflow to be run manually from the Actions tab
  workflow_dispatch:

defaults:
  run:
    working-directory: ./projectApp
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out the repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: npm ci

      - name: Run linter
        run: npm run lint

      - name: Build
        run: npm run build

      - name: Test
        run: cd test && npm run test