#  Continuous Integration (CI) workflow to build and test our project
#  This workflow will run on every push to the repository and on every pull request

name: Build and Test
# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events
  push:
    branches: ['**']
  pull_request:
    branches: ['**']
  # Allows this workflow to be run manually from the Actions tab
  workflow_dispatch:

defaults:
  run:
    working-directory: ./projectApp
jobs:
  job-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: npm ci

      # Build
      - name: Run Prettier
        run: npm run prettier:check
      - name: Run linters
        run: | 
          npm run lint
          npm run lint:gherkin
      - name: Build
        run: npm run build

      # Starting tests. Fire up logging server
      - name: Start up logging server
        run: npx pm2 start logger-server.js --name logger
      # Run unit tests
      - name: Run unit tests
        run: npm run unittests
      # Run smoke tests / integration tests
      - name: Run smoketests
        run: npm run smoketests
        # Run log parsing tests
      - name: Run log parsing tests
        run: npm run logtests
      # Kill logging server
      - name: Kill logging server
        run: npx pm2 delete logger

#  job-windows: permanently removed from workflow

  # Elastic running at OC during term
  send-logs-to-elastic:
      runs-on: ubuntu-latest
      needs: [job-linux]
      if: always()
      steps:
        - name: Checkout code
          uses: actions/checkout@v4
        - name: Set up Node.js
          uses: actions/setup-node@v4
          with:
            node-version: '20'
        - name: Install dependencies
          run: npm install
        - name: Upload GitHub Action workflows logs to elastic
          uses: loop1dev/github-actions-to-elk@v1.0.0
          with:
            githubToken: "${{ secrets.GITHUB }}"
            githubOrg: "UniversityOfSaskatchewanCMPT371"
            githubRepository: "term-project-2025-team-1"
            githubRunId: "${{ github.run_id }}"
            elasticHost: "${{ secrets.ELASTIC_HOST }}"
            elasticApiKeyId: "${{ secrets.ELASTIC_KEY_ID }}"
            elasticApiKey: "${{ secrets.ELASTIC_API_KEY }}"
            elasticIndex: "ci-cd"
