#  Continuous Integration (CI) workflow to build and test our TS/JS project
name: BuildandTest

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events
  push:
    branches: ['**']
  pull_request:
    branches: ['**']

  # Allows this workflow to be run manually from the Actions tab
  workflow_dispatch:

defaults:
  run:
    working-directory: ./projectApp
jobs:
  job-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: npm ci

      - name: Run linter
        run: npm run lint

      - name: Build
        run: npm run build

      - name: Test
        run: npm run test

#  job-windows:
#    runs-on: windows-latest
#    steps:
#      - uses: actions/checkout@v4
#
#      - name: Install dependencies
#        run: npm ci
#
#      - name: Run linter
#        run: npm run lint
#
#      - name: Build
#        run: npm run build
#
#      - name: Test
#        run: |
#         npm run test
#        env:
#          CI: true
#        timeout-minutes: 3