name: Manually Deploy to Firebase Hosting
on:
  workflow_dispatch:
defaults:
  run:
    working-directory: ./projectApp
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run the build, lint, test flow
        run: |
          npm ci
          npm run lint
          npm run build
          npx pm2 start logger-server.js --name logger
          npm run test
          npx pm2 delete logger
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_CMPT371_2025_T1 }}
          entryPoint: './projectApp'
          channelId: live
          projectId: cmpt371-2025-t1